### ISSUE TITLE
Metal Drag&Drop doesn't support dragging from the scrollable divs

### ISSUE THREAD

**Issue by pavel-savinov** [metal/metal-drag-drop#6]
Now metal-drag-drop doesn't support dragging from the scrollable div(see video attached).
[LPS-75403.webm.zip](https://github.com/metal/metal-drag-drop/files/1406369/LPS-75403.webm.zip)

Metal DD demo page to test the behaviour also attached.
[dragScrollable.html.zip](https://github.com/metal/metal-drag-drop/files/1406381/dragScrollable.html.zip)

It would be great to be able to define dragPlaceholder like CLONE, but to clone the active drag in body, not in the parent element.

**Comment by jbalsas** [comment]
This should be working now with https://github.com/metal/metal-drag-drop/pull/13 and will be released in `3.0.0`
