### ISSUE TITLE
Dragged elements are lost if component is updated during dragging

### ISSUE THREAD

**Issue by p2kmgcl** [metal/metal-drag-drop#7]
If metal-drag-drop is used inside a metal component, and this component is rendered while dragging an element, the generated cloned node is lost, as metal rerenders the component's content.

Here you have a use case of what I am trying to do:

1. We have a list of sortable elements, any element can be dragged, and then it is appended to the end of the list
2. When an element starts being dragged, it is faded, so the user sees which is the source
3. A "preview" of the position where the element is going to be dropped is shown (just a few dashes at the end of the list)
4. On drop, the preview is destroyed and the element is moved to the end of the list

Code for the use case: https://github.com/p2kmgcl/metal-drag-drop-request

**Comment by jbalsas** [comment]
This should be working now with https://github.com/metal/metal-drag-drop/pull/13 and will be released in `3.0.0`
